import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service · Debrief",
  description: "The terms for using Debrief.",
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="August 2026"
      intro="By using Debrief you agree to these terms. They are intentionally short: Debrief is a learning tool, offered as-is, to help you test and strengthen your own understanding."
      sections={[
        {
          heading: "What Debrief is for",
          body: (
            <p>
              Debrief helps you learn by explaining concepts in your own words
              and seeing where an explanation stops holding. It is an educational
              aid, not a source of professional, medical, legal, or financial
              advice. Use your own judgment for anything that matters.
            </p>
          ),
        },
        {
          heading: "AI-generated feedback",
          body: (
            <p>
              The questions, corrections, and understanding map are generated by
              a language model. They are usually helpful but can be incomplete or
              wrong. Treat the feedback as a prompt to think harder, not as a
              final authority, and verify anything you intend to rely on.
            </p>
          ),
        },
        {
          heading: "Acceptable use",
          body: (
            <p>
              Don&apos;t use Debrief to submit unlawful content or to attempt to
              disrupt, overload, or reverse-engineer the service. Access may be
              rate-limited or withdrawn to keep the tool working for everyone.
            </p>
          ),
        },
        {
          heading: "No warranty",
          body: (
            <p>
              Debrief is provided &ldquo;as is,&rdquo; without warranties of any
              kind, and may change or be unavailable at any time. To the extent
              permitted by law, the project and its authors are not liable for
              any loss arising from its use.
            </p>
          ),
        },
      ]}
    />
  );
}
